### ISSUE TITLE
[Request] Remove status when idle

### ISSUE THREAD

**Issue by NomNuggetNom** [Almighty-Alpaca/Intellij-Discord-Integration#10]
If you go idle, or your computer is locked, etc, then your status should be removed.

**Comment by Mdstumpfy123** [comment]
Hmmm

**Comment by Almighty-Alpaca** [comment]
I'll try to integrate this into the settings menu that is coming in the next version.

**Comment by Almighty-Alpaca** [comment]
This has been implemented in 36f2e93.
