### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by checkium** [Almighty-Alpaca/Intellij-Discord-Integration#11]
I've tried reinstalling the plugin, reenabling it, readd intellij on discord settings and also restart IntellIj IDEA multiple times, but the rich presence doesn't seem to be working, it only shows the playing status with no rich presence, I've checked intellij logs and there's nothing related to the plugin except the plugin list.

**Comment by Almighty-Alpaca** [comment]
Could you provide a bit more information so I can actually try to help you?
Useful information includes but is not limited to:
-Plugin Version
-IDE + Version
-OS
-Discord Client (Stable/PTB/Canary), one or more

**Comment by checkium** [comment]
Plugin version 0.4.0
IntellIj IDEA 2017.3.1
Windows 10
Stable & Canary installed, running canary build 8746

**Comment by Almighty-Alpaca** [comment]
Sorry for the late response, didn't get to it earlier. Anyway, the exact same configuration works perfectly for me.
Do you get any error notification(s)?
If not my next guess would be that you start IntelliJ before Discord but in order to detect the RPC connection Discord has to be started first.

**Comment by checkium** [comment]
I tried closing both IDEA and Discord, then start up discord and when it was open start IDEA, and it still doesn't work. IDEA doesn't throw any error notifications also.

**Comment by Almighty-Alpaca** [comment]
That is weird. Can you check if other RPC applications work for you?

**Comment by checkium** [comment]
I used my spotify integration to test it out and it seems that the auto register doesn't get the app added to the games list and the ready callback is never called.

**Comment by Almighty-Alpaca** [comment]
If your Spotify integration also doesn't work it seems like a client issue. You should try reinstalling the client, it helped fixing many different problems in the past.

**Comment by checkium** [comment]
I've reinstalled discord and it works now, thank you for the help.

**Comment by NathanCheshire** [comment]
I currently am having this issue. Reinstalling discord did not fix the issue. Spotify integration, Lunar client integration, and all other RPC connections function as intended.

**Comment by xFedeT** [comment]
> I currently am having this issue. Reinstalling discord did not fix the issue. Spotify integration, Lunar client integration, and all other RPC connections function as intended.

Same

**Comment by AlizerUncaged** [comment]
any fixes for this?

**Comment by AlgeRiany01** [comment]
same issue

**Comment by gitnickolson** [comment]
+1
