### ISSUE TITLE
Switch between open projects

### ISSUE THREAD

**Issue by napstr** [Almighty-Alpaca/Intellij-Discord-Integration#12]
The extension seems to only work with the last opened project. Minimizing it and working on another, earlier opened one, does not update the status, it keeps showing one's status as editing the minimized project which one is not working on actually.

**Comment by Almighty-Alpaca** [comment]
I'll see what I can do.

**Comment by Almighty-Alpaca** [comment]
This has been resolved in e838212. If you still experience this behavior in the next version feel free to reopen this issue.

**Comment by napstr** [comment]
Seems to be working :+1:

**Comment by Almighty-Alpaca** [comment]
:ok_hand:
