### ISSUE TITLE
Support .sh extension

### ISSUE THREAD

**Issue by Frederikam** [Almighty-Alpaca/Intellij-Discord-Integration#18]
Please add support for .sh files. The icon could be a simple shebang `#!`

**Comment by Almighty-Alpaca** [comment]
Sure, but just as #17 this will also have to wait until Discord has fixed their asset manager.

**Comment by Frederikam** [comment]
👌

**Comment by Almighty-Alpaca** [comment]
Wouldn't the [official bash logo](https://github.com/odb/official-bash-logo) fit even better than a `#!` ?
