### ISSUE TITLE
Crashing on macOS Sierra

### ISSUE THREAD

**Issue by GeoffreyWesthoff** [Almighty-Alpaca/Intellij-Discord-Integration#2]
OS: macOS Sierra 10.12.4
IntelliJ: PyCharm 2017.3

Error logs:

[Image 1](http://je-moeder.is-een-plopkoek.xyz/uhbEt0.png)
[Image 2](http://je-moeder.is-een-plopkoek.xyz/N2qbva.png)

It seems it cannot find Discord's RPC libary?

**Comment by Almighty-Alpaca** [comment]
Your stack trace indicates you're using an oudated (probably self compiled) version. Only the latest commit ( 57eee0d/[v0.1.0](https://github.com/Almighty-Alpaca/Intellij-Discord-Integration/releases/tag/v0.1.0)) adds support for macOS.

**Comment by GeoffreyWesthoff** [comment]
I am using this release
[Screenshot](https://user-images.githubusercontent.com/22159739/33509225-02160c2a-d700-11e7-9a7d-49e2c67e75c0.png)

**Comment by Almighty-Alpaca** [comment]
My bad, thought that stack trace belongs to an old version.

Unfortunately I don't have a Mac so I can't test it myself that well. I'll set up a VM later today, hopefully that helps tracking down the issue.

**Comment by Almighty-Alpaca** [comment]
So after some testing I'm still not sure why v0.1.0 didn't work, but at least v0.2.0 works perfectly for me. It has been released ~1 day ago, but it has yet to be approved by Jetbrains to appear in their plugin repository. It is available in the [release page](https://github.com/Almighty-Alpaca/Intellij-Discord-Integration/releases/tag/v0.2.0) though.

**Comment by GeoffreyWesthoff** [comment]
The v0.3.0 release fixes this issue, thanks.
