### ISSUE TITLE
[Error] Initialization fails.

### ISSUE THREAD

**Issue by Sanduhr32** [Almighty-Alpaca/Intellij-Discord-Integration#21]
Stacktrace: [hastebin](https://hastebin.com/utuyugulag.pl)
Note: jar file of release 0.7.0 may miss dependencies

**Comment by fabbe50** [comment]
Having the same issue

**Comment by Almighty-Alpaca** [comment]
I deleted the update from the jetbrains repo for now and will upload a fixed one later today.

**Comment by MinnDevelopment** [comment]
In the meantime you can use the [release build](https://github.com/Almighty-Alpaca/Intellij-Discord-Integration/releases/download/v0.7.0/Jetbrains-Discord-Integration-0.7.0.zip)

**Comment by Almighty-Alpaca** [comment]
Yeah, fixed that artifact a few hours ago. I've now also pushed v0.7.1 so that as soon as it's approved everyone who already downloaded v0.7.0 will get the update notification.

**Comment by Almighty-Alpaca** [comment]
This has been fixed as of a few days ago
