### ISSUE TITLE
[Feature Request] Don't show file

### ISSUE THREAD

**Issue by epvpsyc** [Almighty-Alpaca/Intellij-Discord-Integration#23]
Would be great if you could add a setting which gives the option to remove the 'editing file.xyz' paragraph

**Comment by Almighty-Alpaca** [comment]
Added this to my to-do list

**Comment by Almighty-Alpaca** [comment]
I plan to implement #24 and #30 before creating the next release. Will get to it until the weekend hopefully.

**Comment by Almighty-Alpaca** [comment]
Sorry this took so long, have been way too busy for my taste. I'm going to publish the release now but as always it might take 1-2 days until Jetbrains makes it available in their plugin repo.
