### ISSUE TITLE
The ability to set a project description?

### ISSUE THREAD

**Issue by wherkamp** [Almighty-Alpaca/Intellij-Discord-Integration#24]
So I can add a little description about what I am working on.

**Comment by Almighty-Alpaca** [comment]
While I do like the idea I don't think this is possible. Discord's Rich Presence only offers a limited number of fields:
![rp-profile-view.png](https://raw.githubusercontent.com/discordapp/discord-rpc/master/documentation/images/rp-profile-view.png)
In addition to that every field has a max length of 128 characters, so adding it to the field with the project name would limit it to <100 chars probably. Besides the client has a very limited space anyway so it only shows the full text if you hover over it.

**Comment by wherkamp** [comment]
Well have it as a option instead of having the current file editing.

**Comment by Almighty-Alpaca** [comment]
That should actually be possible, you'd just have to set the description for each project in the settings. Might implement this together with #23.

**Comment by wherkamp** [comment]
Awesome Thank you!
