### ISSUE TITLE
When working on a file without an extension, RichPresence provides the extension as `null`

### ISSUE THREAD

**Issue by TheMonitorLizard** [Almighty-Alpaca/Intellij-Discord-Integration#3]
Example:
![](https://kass.is-pretty.sexy/ffcf3b.png)
Where the file is actually called `LICENSE` (no extension)

Also there is an issue when the file has a dual (or pseudo) extension
Example:
![](https://kass.is-pretty.sexy/639363.png)

**Comment by Almighty-Alpaca** [comment]
Good catch. Will fix this later today.
