### ISSUE TITLE
Not showing files

### ISSUE THREAD

**Issue by TransmissionsDev** [Almighty-Alpaca/Intellij-Discord-Integration#35]
Hey! 

I love this plugin but with these settings:

![screenshot- 190](https://user-images.githubusercontent.com/26209401/39503531-49caf192-4d7b-11e8-903b-e2cd51e19775.png)

My presence appears like so:

![screenshot- 191](https://user-images.githubusercontent.com/26209401/39503581-8991d53e-4d7b-11e8-88d1-35c3c65b5b95.png)

The file i'm editing is not showing up!

(Even when I make the description blank)

**Comment by nitrog0d** [comment]
^

**Comment by TransmissionsDev** [comment]
Thanks @nitrog0d removing the discord.xml file worked!

**Comment by Almighty-Alpaca** [comment]
This bug is [known](https://github.com/Almighty-Alpaca/Intellij-Discord-Integration/issues/31) has already been fixed. Should've probably made a new release with it sooner, gonna catch up on that later.
