### ISSUE TITLE
Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by havasuit** [Almighty-Alpaca/Intellij-Discord-Integration#39]
I've tried with different IDE's but it doesn't seem to function on Ubuntu 18.04. I'm not sure about 16.04, was this designed with Ubuntu in mind? If not, is this something that could be fixed?

**Comment by MinnDevelopment** [comment]
Works fine on my 18.04 installation, make sure you don't use the version from snap/software center.

**Comment by havasuit** [comment]
Yep, thanks - that sorted it.
