### ISSUE TITLE
Timer restarts at 24h mark

### ISSUE THREAD

**Issue by gitnickolson** [Almighty-Alpaca/Intellij-Discord-Integration#405]
Please make the timer go past 24h.
I want to show people that I don't have anything better to do.

You could achieve this by switching to a day/weeks/months format (Playing for 1 day, playing for 1 week, playing for 1 month) if you don't have the possibility to let the timer go beyond 24h because of a cap on discords side!

**Comment by nicokempe** [comment]
+1

**Comment by nikolan123** [comment]
I'm pretty sure that's a Discord limitation since my custom RP tool does the same, not sure tho. Would be nice to see if it's possible

**Comment by gitnickolson** [comment]
Absolutely!

**Comment by gitnickolson** [comment]
With the latest discord update, this issue is basically resolved 👍🏻.
<img width="282" alt="grafik" src="https://github.com/user-attachments/assets/f0c99e1d-8e25-467a-88c3-34398ba330b8">
