### ISSUE TITLE
Language C not displayed

### ISSUE THREAD

**Issue by MrSquaare** [Almighty-Alpaca/Intellij-Discord-Integration#42]
When a c file is opened, the presence is not updated

**Comment by Almighty-Alpaca** [comment]
What file extension has that file?

**Comment by Almighty-Alpaca** [comment]
Quite a few have been added only recently in #40 and aren't in a release version yet.

**Comment by AregevDev** [comment]
a .c file

**Comment by MrSquaare** [comment]
> a .c file

Yes, .c files (and .h files too)
I tried to open a .c file with PhpStorm to see if it came from CLion and I still have the problem

**Comment by AregevDev** [comment]
Well c++ is working if I remember correctly

**Comment by AregevDev** [comment]
Can you check it?

**Comment by AregevDev** [comment]
Also check .hpp

**Comment by MinnDevelopment** [comment]
The issue with the `.c` extension is that the language text is only `C` causing it to fail. `large_image_text` has to be at least 2 characters long.

**Comment by Almighty-Alpaca** [comment]
Oh I didn't know that, gonna fix soon:tm:
