### ISSUE TITLE
Add the Kotlin language ;)

### ISSUE THREAD

**Issue by tim54000** [Almighty-Alpaca/Intellij-Discord-Integration#6]
Just add the Kotlin language on your project please =)

Else I like this project !

**Comment by Almighty-Alpaca** [comment]
If you are referring to the large image in the rich presence Kotlin is already supported. Although the version (v0.2.0) that adds those images has been released about 2 days ago it hasn't been approved by Jetbrains yet and won't appear in the IDE's plugin browsers until then.
You can already download it from the [release](https://github.com/Almighty-Alpaca/Intellij-Discord-Integration/releases/tag/v0.2.0) page though.

**Comment by tim54000** [comment]
Ohh Sorry, I don’t view it 😊. 
Good luck !

Provenance : Courrier pour Windows 10

De : Aljoscha Grebe
Envoyé le :dimanche 3 décembre 2017 15:05
À : Almighty-Alpaca/Intellij-Discord-Integration
Cc : tim54000; Author
Objet :Re: [Almighty-Alpaca/Intellij-Discord-Integration] Add the Kotlinlanguage ;) (#6)

If you are referring to the large image in the rich presence Kotlin is already supported. Although the version (v0.2.0) that adds those images has been released about 2 days ago it hasn't been approved by Jetbrains yet and won't appear in the IDE's plugin browsers until then.
You can already download it from the release page though.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
