### ISSUE TITLE
[Request] Elapsed time

### ISSUE THREAD

**Issue by Mdstumpfy123** [Almighty-Alpaca/Intellij-Discord-Integration#7]
Hello Almighty Alpaca,
If it is possible can you add a Elapsed time function to the rich presence?

**Comment by Almighty-Alpaca** [comment]
Initially this already used to work util I broke it is a very early commit. I've already fixed it in 90acdfd.
It currently shows the time since the project has been opened but I plan to make this configurable later when I add a settings menu.
